# Generated by Django 4.2 on 2025-10-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastwork', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catreview',
            old_name='username',
            new_name='title',
        ),
    ]
