# Generated by Django 4.2 on 2025-10-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastwork', '0002_rename_username_catreview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catreview',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pastworkalbum',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
