# Generated by Django 4.2 on 2025-10-04 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastwork', '0003_alter_catreview_title_alter_pastworkalbum_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catreview',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
