# Generated by Django 4.2 on 2025-10-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastwork', '0004_alter_catreview_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
