# Generated by Django 4.2 on 2025-10-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastwork', '0005_alter_projectimage_options_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastworkalbum',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
