# Generated by Django 4.2 on 2025-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
